import Vue from 'vue'
import { wrapFunctional } from './utils'

const components = {
  IBadge: () => import('../../node_modules/@inkline/inkline/src/components/IBadge/index.vue' /* webpackChunkName: "components/i-badge" */).then(c => wrapFunctional(c.default || c)),
  IAlert: () => import('../../node_modules/@inkline/inkline/src/components/IAlert/index.vue' /* webpackChunkName: "components/i-alert" */).then(c => wrapFunctional(c.default || c)),
  IBreadcrumbItem: () => import('../../node_modules/@inkline/inkline/src/components/IBreadcrumbItem/index.vue' /* webpackChunkName: "components/i-breadcrumb-item" */).then(c => wrapFunctional(c.default || c)),
  IBreadcrumb: () => import('../../node_modules/@inkline/inkline/src/components/IBreadcrumb/index.vue' /* webpackChunkName: "components/i-breadcrumb" */).then(c => wrapFunctional(c.default || c)),
  IButton: () => import('../../node_modules/@inkline/inkline/src/components/IButton/index.vue' /* webpackChunkName: "components/i-button" */).then(c => wrapFunctional(c.default || c)),
  IButtonGroup: () => import('../../node_modules/@inkline/inkline/src/components/IButtonGroup/index.vue' /* webpackChunkName: "components/i-button-group" */).then(c => wrapFunctional(c.default || c)),
  ICard: () => import('../../node_modules/@inkline/inkline/src/components/ICard/index.vue' /* webpackChunkName: "components/i-card" */).then(c => wrapFunctional(c.default || c)),
  ICheckable: () => import('../../node_modules/@inkline/inkline/src/components/ICheckable/index.vue' /* webpackChunkName: "components/i-checkable" */).then(c => wrapFunctional(c.default || c)),
  ICheckableGroup: () => import('../../node_modules/@inkline/inkline/src/components/ICheckableGroup/index.vue' /* webpackChunkName: "components/i-checkable-group" */).then(c => wrapFunctional(c.default || c)),
  ICheckbox: () => import('../../node_modules/@inkline/inkline/src/components/ICheckbox/index.vue' /* webpackChunkName: "components/i-checkbox" */).then(c => wrapFunctional(c.default || c)),
  ICheckboxButton: () => import('../../node_modules/@inkline/inkline/src/components/ICheckboxButton/index.vue' /* webpackChunkName: "components/i-checkbox-button" */).then(c => wrapFunctional(c.default || c)),
  ICheckboxButtonGroup: () => import('../../node_modules/@inkline/inkline/src/components/ICheckboxButtonGroup/index.vue' /* webpackChunkName: "components/i-checkbox-button-group" */).then(c => wrapFunctional(c.default || c)),
  ICheckboxGroup: () => import('../../node_modules/@inkline/inkline/src/components/ICheckboxGroup/index.vue' /* webpackChunkName: "components/i-checkbox-group" */).then(c => wrapFunctional(c.default || c)),
  ICollapsible: () => import('../../node_modules/@inkline/inkline/src/components/ICollapsible/index.vue' /* webpackChunkName: "components/i-collapsible" */).then(c => wrapFunctional(c.default || c)),
  ICollapsibleItem: () => import('../../node_modules/@inkline/inkline/src/components/ICollapsibleItem/index.vue' /* webpackChunkName: "components/i-collapsible-item" */).then(c => wrapFunctional(c.default || c)),
  IColumn: () => import('../../node_modules/@inkline/inkline/src/components/IColumn/index.vue' /* webpackChunkName: "components/i-column" */).then(c => wrapFunctional(c.default || c)),
  IContainer: () => import('../../node_modules/@inkline/inkline/src/components/IContainer/index.vue' /* webpackChunkName: "components/i-container" */).then(c => wrapFunctional(c.default || c)),
  IDatatable: () => import('../../node_modules/@inkline/inkline/src/components/IDatatable/index.vue' /* webpackChunkName: "components/i-datatable" */).then(c => wrapFunctional(c.default || c)),
  IDropdown: () => import('../../node_modules/@inkline/inkline/src/components/IDropdown/index.vue' /* webpackChunkName: "components/i-dropdown" */).then(c => wrapFunctional(c.default || c)),
  IDropdownDivider: () => import('../../node_modules/@inkline/inkline/src/components/IDropdownDivider/index.vue' /* webpackChunkName: "components/i-dropdown-divider" */).then(c => wrapFunctional(c.default || c)),
  IDropdownItem: () => import('../../node_modules/@inkline/inkline/src/components/IDropdownItem/index.vue' /* webpackChunkName: "components/i-dropdown-item" */).then(c => wrapFunctional(c.default || c)),
  IDropdownMenu: () => import('../../node_modules/@inkline/inkline/src/components/IDropdownMenu/index.vue' /* webpackChunkName: "components/i-dropdown-menu" */).then(c => wrapFunctional(c.default || c)),
  IForm: () => import('../../node_modules/@inkline/inkline/src/components/IForm/index.vue' /* webpackChunkName: "components/i-form" */).then(c => wrapFunctional(c.default || c)),
  IFormError: () => import('../../node_modules/@inkline/inkline/src/components/IFormError/index.vue' /* webpackChunkName: "components/i-form-error" */).then(c => wrapFunctional(c.default || c)),
  IFormGroup: () => import('../../node_modules/@inkline/inkline/src/components/IFormGroup/index.vue' /* webpackChunkName: "components/i-form-group" */).then(c => wrapFunctional(c.default || c)),
  IFormLabel: () => import('../../node_modules/@inkline/inkline/src/components/IFormLabel/index.vue' /* webpackChunkName: "components/i-form-label" */).then(c => wrapFunctional(c.default || c)),
  IHamburgerMenu: () => import('../../node_modules/@inkline/inkline/src/components/IHamburgerMenu/index.vue' /* webpackChunkName: "components/i-hamburger-menu" */).then(c => wrapFunctional(c.default || c)),
  IHeader: () => import('../../node_modules/@inkline/inkline/src/components/IHeader/index.vue' /* webpackChunkName: "components/i-header" */).then(c => wrapFunctional(c.default || c)),
  IIcon: () => import('../../node_modules/@inkline/inkline/src/components/IIcon/index.vue' /* webpackChunkName: "components/i-icon" */).then(c => wrapFunctional(c.default || c)),
  IInput: () => import('../../node_modules/@inkline/inkline/src/components/IInput/index.vue' /* webpackChunkName: "components/i-input" */).then(c => wrapFunctional(c.default || c)),
  IInputNumber: () => import('../../node_modules/@inkline/inkline/src/components/IInputNumber/index.vue' /* webpackChunkName: "components/i-input-number" */).then(c => wrapFunctional(c.default || c)),
  ILayout: () => import('../../node_modules/@inkline/inkline/src/components/ILayout/index.vue' /* webpackChunkName: "components/i-layout" */).then(c => wrapFunctional(c.default || c)),
  ILayoutAside: () => import('../../node_modules/@inkline/inkline/src/components/ILayoutAside/index.vue' /* webpackChunkName: "components/i-layout-aside" */).then(c => wrapFunctional(c.default || c)),
  ILayoutContent: () => import('../../node_modules/@inkline/inkline/src/components/ILayoutContent/index.vue' /* webpackChunkName: "components/i-layout-content" */).then(c => wrapFunctional(c.default || c)),
  ILayoutFooter: () => import('../../node_modules/@inkline/inkline/src/components/ILayoutFooter/index.vue' /* webpackChunkName: "components/i-layout-footer" */).then(c => wrapFunctional(c.default || c)),
  ILayoutHeader: () => import('../../node_modules/@inkline/inkline/src/components/ILayoutHeader/index.vue' /* webpackChunkName: "components/i-layout-header" */).then(c => wrapFunctional(c.default || c)),
  ILinkable: () => import('../../node_modules/@inkline/inkline/src/components/ILinkable/index.vue' /* webpackChunkName: "components/i-linkable" */).then(c => wrapFunctional(c.default || c)),
  IListGroup: () => import('../../node_modules/@inkline/inkline/src/components/IListGroup/index.vue' /* webpackChunkName: "components/i-list-group" */).then(c => wrapFunctional(c.default || c)),
  IListGroupItem: () => import('../../node_modules/@inkline/inkline/src/components/IListGroupItem/index.vue' /* webpackChunkName: "components/i-list-group-item" */).then(c => wrapFunctional(c.default || c)),
  ILoader: () => import('../../node_modules/@inkline/inkline/src/components/ILoader/index.vue' /* webpackChunkName: "components/i-loader" */).then(c => wrapFunctional(c.default || c)),
  IMedia: () => import('../../node_modules/@inkline/inkline/src/components/IMedia/index.vue' /* webpackChunkName: "components/i-media" */).then(c => wrapFunctional(c.default || c)),
  IModal: () => import('../../node_modules/@inkline/inkline/src/components/IModal/index.vue' /* webpackChunkName: "components/i-modal" */).then(c => wrapFunctional(c.default || c)),
  INav: () => import('../../node_modules/@inkline/inkline/src/components/INav/index.vue' /* webpackChunkName: "components/i-nav" */).then(c => wrapFunctional(c.default || c)),
  INavItem: () => import('../../node_modules/@inkline/inkline/src/components/INavItem/index.vue' /* webpackChunkName: "components/i-nav-item" */).then(c => wrapFunctional(c.default || c)),
  INavbar: () => import('../../node_modules/@inkline/inkline/src/components/INavbar/index.vue' /* webpackChunkName: "components/i-navbar" */).then(c => wrapFunctional(c.default || c)),
  INavbarBrand: () => import('../../node_modules/@inkline/inkline/src/components/INavbarBrand/index.vue' /* webpackChunkName: "components/i-navbar-brand" */).then(c => wrapFunctional(c.default || c)),
  INavbarItems: () => import('../../node_modules/@inkline/inkline/src/components/INavbarItems/index.vue' /* webpackChunkName: "components/i-navbar-items" */).then(c => wrapFunctional(c.default || c)),
  IPagination: () => import('../../node_modules/@inkline/inkline/src/components/IPagination/index.vue' /* webpackChunkName: "components/i-pagination" */).then(c => wrapFunctional(c.default || c)),
  IPopover: () => import('../../node_modules/@inkline/inkline/src/components/IPopover/index.vue' /* webpackChunkName: "components/i-popover" */).then(c => wrapFunctional(c.default || c)),
  IProgress: () => import('../../node_modules/@inkline/inkline/src/components/IProgress/index.vue' /* webpackChunkName: "components/i-progress" */).then(c => wrapFunctional(c.default || c)),
  IProgressBar: () => import('../../node_modules/@inkline/inkline/src/components/IProgressBar/index.vue' /* webpackChunkName: "components/i-progress-bar" */).then(c => wrapFunctional(c.default || c)),
  IRadio: () => import('../../node_modules/@inkline/inkline/src/components/IRadio/index.vue' /* webpackChunkName: "components/i-radio" */).then(c => wrapFunctional(c.default || c)),
  IRadioButton: () => import('../../node_modules/@inkline/inkline/src/components/IRadioButton/index.vue' /* webpackChunkName: "components/i-radio-button" */).then(c => wrapFunctional(c.default || c)),
  IRadioButtonGroup: () => import('../../node_modules/@inkline/inkline/src/components/IRadioButtonGroup/index.vue' /* webpackChunkName: "components/i-radio-button-group" */).then(c => wrapFunctional(c.default || c)),
  IRadioGroup: () => import('../../node_modules/@inkline/inkline/src/components/IRadioGroup/index.vue' /* webpackChunkName: "components/i-radio-group" */).then(c => wrapFunctional(c.default || c)),
  IRow: () => import('../../node_modules/@inkline/inkline/src/components/IRow/index.vue' /* webpackChunkName: "components/i-row" */).then(c => wrapFunctional(c.default || c)),
  ISelect: () => import('../../node_modules/@inkline/inkline/src/components/ISelect/index.vue' /* webpackChunkName: "components/i-select" */).then(c => wrapFunctional(c.default || c)),
  ISelectOption: () => import('../../node_modules/@inkline/inkline/src/components/ISelectOption/index.vue' /* webpackChunkName: "components/i-select-option" */).then(c => wrapFunctional(c.default || c)),
  ISidebar: () => import('../../node_modules/@inkline/inkline/src/components/ISidebar/index.vue' /* webpackChunkName: "components/i-sidebar" */).then(c => wrapFunctional(c.default || c)),
  ITab: () => import('../../node_modules/@inkline/inkline/src/components/ITab/index.vue' /* webpackChunkName: "components/i-tab" */).then(c => wrapFunctional(c.default || c)),
  ITable: () => import('../../node_modules/@inkline/inkline/src/components/ITable/index.vue' /* webpackChunkName: "components/i-table" */).then(c => wrapFunctional(c.default || c)),
  ITabs: () => import('../../node_modules/@inkline/inkline/src/components/ITabs/index.vue' /* webpackChunkName: "components/i-tabs" */).then(c => wrapFunctional(c.default || c)),
  ITextarea: () => import('../../node_modules/@inkline/inkline/src/components/ITextarea/index.vue' /* webpackChunkName: "components/i-textarea" */).then(c => wrapFunctional(c.default || c)),
  IToggle: () => import('../../node_modules/@inkline/inkline/src/components/IToggle/index.vue' /* webpackChunkName: "components/i-toggle" */).then(c => wrapFunctional(c.default || c)),
  ITooltip: () => import('../../node_modules/@inkline/inkline/src/components/ITooltip/index.vue' /* webpackChunkName: "components/i-tooltip" */).then(c => wrapFunctional(c.default || c))
}

for (const name in components) {
  Vue.component(name, components[name])
  Vue.component('Lazy' + name, components[name])
}
