export const data = JSON.parse("{\"key\":\"v-0cd8ca55\",\"path\":\"/dev/tutorials/cross-chain-tutorial.html\",\"title\":\"Cross-chain governance\",\"lang\":\"en-US\",\"frontmatter\":{\"description\":\"This tutorial serves as an example of how to implement L1 to L2 contract interaction. The following functionality is implemented in this tutorial: A \\\"counter\\\" smart contract is ...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/dev/tutorials/cross-chain-tutorial.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Cross-chain governance\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"This tutorial serves as an example of how to implement L1 to L2 contract interaction. The following functionality is implemented in this tutorial: A \\\"counter\\\" smart contract is ...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}]]},\"headers\":[{\"level\":2,\"title\":\"Preliminaries\",\"slug\":\"preliminaries\",\"link\":\"#preliminaries\",\"children\":[]},{\"level\":2,\"title\":\"Project structure\",\"slug\":\"project-structure\",\"link\":\"#project-structure\",\"children\":[]},{\"level\":2,\"title\":\"L1 governance\",\"slug\":\"l1-governance\",\"link\":\"#l1-governance\",\"children\":[{\"level\":3,\"title\":\"Deploy L1 governance contract\",\"slug\":\"deploy-l1-governance-contract\",\"link\":\"#deploy-l1-governance-contract\",\"children\":[]}]},{\"level\":2,\"title\":\"L2 counter\",\"slug\":\"l2-counter\",\"link\":\"#l2-counter\",\"children\":[]},{\"level\":2,\"title\":\"Reading the counter value\",\"slug\":\"reading-the-counter-value\",\"link\":\"#reading-the-counter-value\",\"children\":[{\"level\":3,\"title\":\"Getting the ABI of the counter contract\",\"slug\":\"getting-the-abi-of-the-counter-contract\",\"link\":\"#getting-the-abi-of-the-counter-contract\",\"children\":[]}]},{\"level\":2,\"title\":\"Calling an L2 contract from L1\",\"slug\":\"calling-an-l2-contract-from-l1\",\"link\":\"#calling-an-l2-contract-from-l1\",\"children\":[{\"level\":3,\"title\":\"Complete code\",\"slug\":\"complete-code\",\"link\":\"#complete-code\",\"children\":[]}]},{\"level\":2,\"title\":\"Complete project\",\"slug\":\"complete-project\",\"link\":\"#complete-project\",\"children\":[]},{\"level\":2,\"title\":\"Learn more\",\"slug\":\"learn-more\",\"link\":\"#learn-more\",\"children\":[]}],\"readingTime\":{\"minutes\":9.72,\"words\":2916},\"filePathRelative\":\"dev/tutorials/cross-chain-tutorial.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
