export const data = JSON.parse("{\"key\":\"v-1054c109\",\"path\":\"/dev/tutorials/custom-paymaster-tutorial.html\",\"title\":\"Building custom paymaster\",\"lang\":\"en-US\",\"frontmatter\":{\"description\":\"Let's see how we can use the paymaster feature to build a custom paymaster that allows users to pay fees in our token. In this tutorial we will: Create a paymaster that will ass...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/dev/tutorials/custom-paymaster-tutorial.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Building custom paymaster\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Let's see how we can use the paymaster feature to build a custom paymaster that allows users to pay fees in our token. In this tutorial we will: Create a paymaster that will ass...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}]]},\"headers\":[{\"level\":2,\"title\":\"Prerequisite\",\"slug\":\"prerequisite\",\"link\":\"#prerequisite\",\"children\":[]},{\"level\":2,\"title\":\"Installing dependencies\",\"slug\":\"installing-dependencies\",\"link\":\"#installing-dependencies\",\"children\":[]},{\"level\":2,\"title\":\"Design\",\"slug\":\"design\",\"link\":\"#design\",\"children\":[{\"level\":3,\"title\":\"Parsing the paymaster input\",\"slug\":\"parsing-the-paymaster-input\",\"link\":\"#parsing-the-paymaster-input\",\"children\":[]},{\"level\":3,\"title\":\"Full code of the paymaster\",\"slug\":\"full-code-of-the-paymaster\",\"link\":\"#full-code-of-the-paymaster\",\"children\":[]}]},{\"level\":2,\"title\":\"Deploying an ERC20 contract\",\"slug\":\"deploying-an-erc20-contract\",\"link\":\"#deploying-an-erc20-contract\",\"children\":[]},{\"level\":2,\"title\":\"Deploying the paymaster\",\"slug\":\"deploying-the-paymaster\",\"link\":\"#deploying-the-paymaster\",\"children\":[]},{\"level\":2,\"title\":\"Using the paymaster\",\"slug\":\"using-the-paymaster\",\"link\":\"#using-the-paymaster\",\"children\":[]},{\"level\":2,\"title\":\"Common errors\",\"slug\":\"common-errors\",\"link\":\"#common-errors\",\"children\":[]},{\"level\":2,\"title\":\"Complete project\",\"slug\":\"complete-project\",\"link\":\"#complete-project\",\"children\":[]},{\"level\":2,\"title\":\"Learn more\",\"slug\":\"learn-more\",\"link\":\"#learn-more\",\"children\":[]}],\"readingTime\":{\"minutes\":7.34,\"words\":2203},\"filePathRelative\":\"dev/tutorials/custom-paymaster-tutorial.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
