export const data = JSON.parse("{\"key\":\"v-2212629a\",\"path\":\"/api/js/accounts-l1-l2.html\",\"title\":\"Accounts: L1->L2 transactions\",\"lang\":\"en-US\",\"frontmatter\":{\"description\":\"This section explores the methods which allow the account (./accounts.md) classes to send transactions from L1 to L2. If you want to get some background on how L1->L2 interactio...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://v2-docs.zksync.io/api/js/accounts-l1-l2.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Accounts: L1->L2 transactions\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"This section explores the methods which allow the account (./accounts.md) classes to send transactions from L1 to L2. If you want to get some background on how L1->L2 interactio...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}]]},\"headers\":[{\"level\":2,\"title\":\"Supported classes\",\"slug\":\"supported-classes\",\"link\":\"#supported-classes\",\"children\":[]},{\"level\":2,\"title\":\"Approving deposit of tokens\",\"slug\":\"approving-deposit-of-tokens\",\"link\":\"#approving-deposit-of-tokens\",\"children\":[{\"level\":3,\"title\":\"Inputs and outputs\",\"slug\":\"inputs-and-outputs\",\"link\":\"#inputs-and-outputs\",\"children\":[]}]},{\"level\":2,\"title\":\"Depositing tokens to zkSync\",\"slug\":\"depositing-tokens-to-zksync\",\"link\":\"#depositing-tokens-to-zksync\",\"children\":[]},{\"level\":2,\"title\":\"Adding native token to zkSync\",\"slug\":\"adding-native-token-to-zksync\",\"link\":\"#adding-native-token-to-zksync\",\"children\":[]},{\"level\":2,\"title\":\"Finalizing withdrawals\",\"slug\":\"finalizing-withdrawals\",\"link\":\"#finalizing-withdrawals\",\"children\":[]},{\"level\":2,\"title\":\"Force-executing transactions on L2\",\"slug\":\"force-executing-transactions-on-l2\",\"link\":\"#force-executing-transactions-on-l2\",\"children\":[{\"level\":3,\"title\":\"Getting the base cost for a transaction\",\"slug\":\"getting-the-base-cost-for-a-transaction\",\"link\":\"#getting-the-base-cost-for-a-transaction\",\"children\":[]}]},{\"level\":2,\"title\":\"Claim Failed Deposit\",\"slug\":\"claim-failed-deposit\",\"link\":\"#claim-failed-deposit\",\"children\":[{\"level\":3,\"title\":\"Input Parameters\",\"slug\":\"input-parameters\",\"link\":\"#input-parameters\",\"children\":[]},{\"level\":3,\"title\":\"Requesting transaction execution\",\"slug\":\"requesting-transaction-execution\",\"link\":\"#requesting-transaction-execution\",\"children\":[]}]}],\"readingTime\":{\"minutes\":3.66,\"words\":1098},\"filePathRelative\":\"api/js/accounts-l1-l2.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
