<template><div><h1 id="getting-started" tabindex="-1"><a class="header-anchor" href="#getting-started" aria-hidden="true">#</a> Getting started</h1>
<h2 id="concept" tabindex="-1"><a class="header-anchor" href="#concept" aria-hidden="true">#</a> Concept</h2>
<p>While most of the existing SDKs should work out of the box, deploying smart contracts or using unique zkSync features, like account abstraction, requires providing additional fields to those that Ethereum transactions have by default.</p>
<p>To provide easy access to all of the features of zkSync 2.0, the <code v-pre>zksync-web3</code> JavaScript SDK was created, which is made in a way that has an interface very similar to those of <a href="https://docs.ethers.io/v5/" target="_blank" rel="noopener noreferrer">ethers<ExternalLinkIcon/></a>. In fact, <code v-pre>ethers</code> is a peer dependency of our library and most of the objects exported by <code v-pre>zksync-web3</code> (e.g. <code v-pre>Wallet</code>, <code v-pre>Provider</code> etc.) inherit from the corresponding <code v-pre>ethers</code> objects and override only the fields that need to be changed.</p>
<p>The library is made in such a way that after replacing <code v-pre>ethers</code> with <code v-pre>zksync-web3</code> most client apps will work out of box.</p>
<h2 id="adding-dependencies" tabindex="-1"><a class="header-anchor" href="#adding-dependencies" aria-hidden="true">#</a> Adding dependencies</h2>
<div class="language-bash line-numbers-mode" data-ext="sh"><pre v-pre class="language-bash"><code><span class="token function">yarn</span> <span class="token function">add</span> zksync-web3
<span class="token function">yarn</span> <span class="token function">add</span> ethers@5 <span class="token comment"># ethers is a peer dependency of zksync-web3</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>Then you can import all the content of the <code v-pre>ethers</code> library and the <code v-pre>zksync-web3</code> library with the following statement:</p>
<div class="language-typescript line-numbers-mode" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token keyword">import</span> <span class="token operator">*</span> <span class="token keyword">as</span> zksync <span class="token keyword">from</span> <span class="token string">"zksync-web3"</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token operator">*</span> <span class="token keyword">as</span> ethers <span class="token keyword">from</span> <span class="token string">"ethers"</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="connecting-to-zksync" tabindex="-1"><a class="header-anchor" href="#connecting-to-zksync" aria-hidden="true">#</a> Connecting to zkSync</h2>
<p>To interact with the zkSync network users need to know the endpoint of the operator node.</p>
<div class="language-typescript line-numbers-mode" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token comment">// Currently, only one environment is supported.</span>
<span class="token keyword">const</span> syncProvider <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">zksync</span><span class="token punctuation">.</span><span class="token function">Provider</span><span class="token punctuation">(</span><span class="token string">"https://zksync2-testnet.zksync.dev"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>Note:</strong> Currently, only <code v-pre>goerli</code> network is supported.</p>
<p>Some operations require access to the Ethereum network. <code v-pre>ethers</code> library should be used to interact with
Ethereum.</p>
<div class="language-typescript line-numbers-mode" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token keyword">const</span> ethProvider <span class="token operator">=</span> ethers<span class="token punctuation">.</span><span class="token function">getDefaultProvider</span><span class="token punctuation">(</span><span class="token string">"goerli"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h2 id="creating-a-wallet" tabindex="-1"><a class="header-anchor" href="#creating-a-wallet" aria-hidden="true">#</a> Creating a wallet</h2>
<p>To control your account in zkSync, use the <code v-pre>zksync.Wallet</code> object. It can sign transactions with keys stored in
<code v-pre>ethers.Wallet</code> and send transaction to the zkSync network using <code v-pre>zksync.Provider</code>.</p>
<div class="language-typescript line-numbers-mode" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token comment">// Derive zksync.Wallet from ethereum private key.</span>
<span class="token comment">// zkSync's wallets support all of the methods of ethers' wallets.</span>
<span class="token comment">// Also, both providers are optional and can be connected to later via `connect` and `connectToL1`.</span>
<span class="token keyword">const</span> syncWallet <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">zksync</span><span class="token punctuation">.</span><span class="token function">Wallet</span><span class="token punctuation">(</span><span class="token constant">PRIVATE_KEY</span><span class="token punctuation">,</span> syncProvider<span class="token punctuation">,</span> ethProvider<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="depositing-funds" tabindex="-1"><a class="header-anchor" href="#depositing-funds" aria-hidden="true">#</a> Depositing funds</h2>
<p>Let's deposit <code v-pre>1.0 ETH</code> to our zkSync account.</p>
<div class="language-typescript line-numbers-mode" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token keyword">const</span> deposit <span class="token operator">=</span> <span class="token keyword">await</span> syncWallet<span class="token punctuation">.</span><span class="token function">deposit</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  token<span class="token operator">:</span> zksync<span class="token punctuation">.</span>utils<span class="token punctuation">.</span><span class="token constant">ETH_ADDRESS</span><span class="token punctuation">,</span>
  amount<span class="token operator">:</span> ethers<span class="token punctuation">.</span>utils<span class="token punctuation">.</span><span class="token function">parseEther</span><span class="token punctuation">(</span><span class="token string">"1.0"</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>NOTE:</strong> Each token inside zkSync has an address. If ERC-20 tokens are being bridged, you should supply the token's L1 address in the <code v-pre>deposit</code> function, or zero address (<code v-pre>0x0000000000000000000000000000000000000000</code>) if you want to deposit ETH. Note, that for the ERC-20 tokens the address of their corresponding L2 token will be different from the one on Ethereum.</p>
<p>After the transaction is submitted to the Ethereum node, its status can be tracked using the transaction handle:</p>
<div class="language-typescript line-numbers-mode" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token comment">// Await processing of the deposit on L1</span>
<span class="token keyword">const</span> ethereumTxReceipt <span class="token operator">=</span> <span class="token keyword">await</span> deposit<span class="token punctuation">.</span><span class="token function">waitL1Commit</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Await processing the deposit on zkSync</span>
<span class="token keyword">const</span> depositReceipt <span class="token operator">=</span> <span class="token keyword">await</span> deposit<span class="token punctuation">.</span><span class="token function">wait</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="checking-zksync-account-balance" tabindex="-1"><a class="header-anchor" href="#checking-zksync-account-balance" aria-hidden="true">#</a> Checking zkSync account balance</h2>
<div class="language-typescript line-numbers-mode" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token comment">// Retreiving the current (committed) balance of an account</span>
<span class="token keyword">const</span> committedEthBalance <span class="token operator">=</span> <span class="token keyword">await</span> syncWallet<span class="token punctuation">.</span><span class="token function">getBalance</span><span class="token punctuation">(</span>zksync<span class="token punctuation">.</span>utils<span class="token punctuation">.</span><span class="token constant">ETH_ADDRESS</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Retrieving the balance of an account in the last finalized block zkSync.md#confirmations-and-finality</span>
<span class="token keyword">const</span> finalizedEthBalance <span class="token operator">=</span> <span class="token keyword">await</span> syncWallet<span class="token punctuation">.</span><span class="token function">getBalance</span><span class="token punctuation">(</span>zksync<span class="token punctuation">.</span>utils<span class="token punctuation">.</span><span class="token constant">ETH_ADDRESS</span><span class="token punctuation">,</span> <span class="token string">"finalized"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>You can read more about what committed and finalized blocks are <RouterLink to="/dev/fundamentals/zkSync.html#confirmations-and-finality">here</RouterLink>.</p>
<h2 id="performing-a-transfer" tabindex="-1"><a class="header-anchor" href="#performing-a-transfer" aria-hidden="true">#</a> Performing a transfer</h2>
<p>Now, let's create a second wallet and transfer some funds into it. Note that it is possible to send assets to any fresh Ethereum
account, without preliminary registration!</p>
<div class="language-typescript line-numbers-mode" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token keyword">const</span> syncWallet2 <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">zksync</span><span class="token punctuation">.</span><span class="token function">Wallet</span><span class="token punctuation">(</span><span class="token constant">PRIVATE_KEY2</span><span class="token punctuation">,</span> syncProvider<span class="token punctuation">,</span> ethProvider<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>Let's transfer <code v-pre>1 ETH</code> to another account:</p>
<p>The <code v-pre>transfer</code> method is a helper method that enables transferring <code v-pre>ETH</code> or any ERC20 token within a single interface.</p>
<div class="language-typescript line-numbers-mode" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token keyword">const</span> amount <span class="token operator">=</span> ethers<span class="token punctuation">.</span>utils<span class="token punctuation">.</span><span class="token function">parseEther</span><span class="token punctuation">(</span><span class="token string">"1.0"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token keyword">const</span> transfer <span class="token operator">=</span> <span class="token keyword">await</span> syncWallet<span class="token punctuation">.</span><span class="token function">transfer</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  to<span class="token operator">:</span> syncWallet2<span class="token punctuation">.</span>address<span class="token punctuation">,</span>
  token<span class="token operator">:</span> zksync<span class="token punctuation">.</span>utils<span class="token punctuation">.</span><span class="token constant">ETH_ADDRESS</span><span class="token punctuation">,</span>
  amount<span class="token punctuation">,</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>To track the status of this transaction:</p>
<div class="language-typescript line-numbers-mode" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token comment">// Await commitment</span>
<span class="token keyword">const</span> transferReceipt <span class="token operator">=</span> <span class="token keyword">await</span> transfer<span class="token punctuation">.</span><span class="token function">wait</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// Await finalization on L1</span>
<span class="token keyword">const</span> transferReceipt <span class="token operator">=</span> <span class="token keyword">await</span> transfer<span class="token punctuation">.</span><span class="token function">waitFinalize</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="withdrawing-funds" tabindex="-1"><a class="header-anchor" href="#withdrawing-funds" aria-hidden="true">#</a> Withdrawing funds</h2>
<p>There are two ways to withdraw funds from zkSync to Ethereum, calling the operation through L2 or L1. If the
withdrawal operation is called through L1, then the operator has a period of time during which he must process
the transaction, otherwise <code v-pre>PriorityMode</code> will be turned on. This ensures that the operator cannot stage the
transaction. But in most cases, a call via L2 is sufficient.</p>
<div class="language-typescript line-numbers-mode" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token keyword">const</span> withdrawL2 <span class="token operator">=</span> <span class="token keyword">await</span> syncWallet<span class="token punctuation">.</span><span class="token function">withdraw</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  token<span class="token operator">:</span> zksync<span class="token punctuation">.</span>utils<span class="token punctuation">.</span><span class="token constant">ETH_ADDRESS</span><span class="token punctuation">,</span>
  amount<span class="token operator">:</span> ethers<span class="token punctuation">.</span>utils<span class="token punctuation">.</span><span class="token function">parseEther</span><span class="token punctuation">(</span><span class="token string">"0.5"</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Assets will be withdrawn to the target wallet after the validity proof of the zkSync block with this transaction is
generated and verified by the mainnet contract.</p>
<p>It is possible to wait until the validity proof verification is complete:</p>
<div class="language-typescript line-numbers-mode" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token keyword">await</span> withdrawL2<span class="token punctuation">.</span><span class="token function">waitFinalize</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h2 id="deploying-a-contract" tabindex="-1"><a class="header-anchor" href="#deploying-a-contract" aria-hidden="true">#</a> Deploying a contract</h2>
<p>A guide on deploying smart contracts using our hardhat plugin is available <a href="../hardhat">here</a>.</p>
<h2 id="adding-tokens-to-the-standard-bridge" tabindex="-1"><a class="header-anchor" href="#adding-tokens-to-the-standard-bridge" aria-hidden="true">#</a> Adding tokens to the standard bridge</h2>
<p>Adding tokens to the zkSync standard bridge can be done in a permissionless way. After adding a token to zkSync, it can be used in all types of transactions.</p>
<p>The documentation on adding tokens to zkSync can be found <RouterLink to="/api/js/accounts-l1-l2.html#adding-native-token-to-zksync">here</RouterLink>.</p>
</div></template>


