<template><div><h1 id="utilities" tabindex="-1"><a class="header-anchor" href="#utilities" aria-hidden="true">#</a> Utilities</h1>
<p><code v-pre>zksync-web3</code> provides some useful utilities for zkSync builders. They can be imported the following way:</p>
<div class="language-typescript line-numbers-mode" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token keyword">import</span> <span class="token punctuation">{</span> utils <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"zksync-web3"</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>Most of the utilities are used internally by the zkSync team. So this document will describe only those which should be helpful for you.</p>
<h2 id="the-address-of-ether" tabindex="-1"><a class="header-anchor" href="#the-address-of-ether" aria-hidden="true">#</a> The &quot;address&quot; of ether</h2>
<p>While formally ether is a token with address <code v-pre>0x000000000000000000000000000000000000800a</code> on zkSync, we use the &quot;zero address&quot; as a more user-friendly alias:</p>
<div class="language-typescript line-numbers-mode" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token keyword">export</span> <span class="token keyword">const</span> <span class="token constant">ETH_ADDRESS</span> <span class="token operator">=</span> <span class="token string">"0x0000000000000000000000000000000000000000"</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h2 id="abi-of-zksync-smart-contract" tabindex="-1"><a class="header-anchor" href="#abi-of-zksync-smart-contract" aria-hidden="true">#</a> ABI of zkSync smart contract</h2>
<div class="language-typescript line-numbers-mode" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token keyword">export</span> <span class="token keyword">const</span> <span class="token constant">ZKSYNC_MAIN_ABI</span> <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">utils</span><span class="token punctuation">.</span><span class="token function">Interface</span><span class="token punctuation">(</span><span class="token keyword">require</span><span class="token punctuation">(</span><span class="token string">"../abi/ZkSync.json"</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h2 id="ierc20-interface" tabindex="-1"><a class="header-anchor" href="#ierc20-interface" aria-hidden="true">#</a> IERC20 interface</h2>
<p>Convenient when interacting with native tokens on zkSync.</p>
<div class="language-typescript line-numbers-mode" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token keyword">export</span> <span class="token keyword">const</span> <span class="token constant">IERC20</span> <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">utils</span><span class="token punctuation">.</span><span class="token function">Interface</span><span class="token punctuation">(</span><span class="token keyword">require</span><span class="token punctuation">(</span><span class="token string">"../abi/IERC20.json"</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h2 id="encoding-paymaster-params" tabindex="-1"><a class="header-anchor" href="#encoding-paymaster-params" aria-hidden="true">#</a> Encoding paymaster params</h2>
<p>Utility method that returns the correctly formed <code v-pre>paymasterParams</code> object for the common <RouterLink to="/dev/developer-guides/aa.html#built-in-paymaster-flows">paymaster flows</RouterLink>.</p>
<div class="language-typescript line-numbers-mode" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token keyword">export</span> <span class="token keyword">function</span> <span class="token function">getPaymasterParams</span><span class="token punctuation">(</span>paymasterAddress<span class="token operator">:</span> Address<span class="token punctuation">,</span> paymasterInput<span class="token operator">:</span> PaymasterInput<span class="token punctuation">)</span><span class="token operator">:</span> PaymasterParams<span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>The definition of the <code v-pre>PaymasterInput</code> can be found <RouterLink to="/api/js/types.html">here</RouterLink>.</p>
<h2 id="default-pubdata-price-limit" tabindex="-1"><a class="header-anchor" href="#default-pubdata-price-limit" aria-hidden="true">#</a> Default pubdata price limit</h2>
<p>Currently, there is no method to accurately estimate the required <code v-pre>ergsPerPubdataLimit</code>. That's why for now, it is highly recommended to provide the <code v-pre>DEFAULT_ERGS_PER_PUBDATA_LIMIT</code>. Users are not charged more by providing it.
Later on it will be possible to query the current recommended limit.</p>
<div class="language-typescript line-numbers-mode" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token keyword">const</span> <span class="token constant">GAS_PER_PUBDATA_BYTE</span> <span class="token operator">=</span> <span class="token number">16</span><span class="token punctuation">;</span>
<span class="token keyword">export</span> <span class="token keyword">const</span> <span class="token constant">DEFAULT_ERGS_PER_PUBDATA_LIMIT</span> <span class="token operator">=</span> <span class="token constant">GAS_PER_PUBDATA_BYTE</span> <span class="token operator">*</span> <span class="token number">10_000</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


