<template><div><h1 id="contract-verification" tabindex="-1"><a class="header-anchor" href="#contract-verification" aria-hidden="true">#</a> Contract Verification</h1>
<h2 id="what-is-contract-verification" tabindex="-1"><a class="header-anchor" href="#what-is-contract-verification" aria-hidden="true">#</a> What is contract verification?</h2>
<p>When you deploy a smart contract on a network, you’re essentially deploying the bytecode produced by the Solidity compiler.</p>
<p>Verifying a contract entails determining whether the on-chain bytecode matches a given source code when it is compiled. If it does, we can state that we have confirmed the bytecode's source code's integrity. Hence the name – verification.</p>
<h2 id="how-are-smart-contracts-verified-in-zksync" tabindex="-1"><a class="header-anchor" href="#how-are-smart-contracts-verified-in-zksync" aria-hidden="true">#</a> How are smart contracts verified in zkSync?</h2>
<p>The deployed bytecode and the Solidity source code of a smart contract are compared during the verification process using zkSync. The algorithm compiles the source code to compare the generated bytecode to the deployed one.
<br>
If the two sides match in every way, the contract is verified.</p>
<p>Code verification requires six arguments:</p>
<ul>
<li>The contract address</li>
<li>The contract name</li>
<li>The source code, including the source of all imports</li>
<li>The version of the compiler used to produce the deployed bytecode</li>
<li>Information about the number of compiler optimizations (if any)</li>
<li>The constructor arguments</li>
</ul>
<p>If any of these pieces of information is wrong, the process of verification fails.</p>
<h2 id="source-code-privacy" tabindex="-1"><a class="header-anchor" href="#source-code-privacy" aria-hidden="true">#</a> Source code privacy</h2>
<p>When your smart contract is deployed on zkSync and verified on the block explorer, users can check the verified source code and interact with it.</p>
<h2 id="verifying-contracts-using-the-zksync-block-explorer" tabindex="-1"><a class="header-anchor" href="#verifying-contracts-using-the-zksync-block-explorer" aria-hidden="true">#</a> Verifying Contracts Using the zkSync Block Explorer</h2>
<p>To get started click the <strong>Tools</strong> tab in the top header, a dropdown will pop up and select <strong>Smart Contract Verification</strong>,  after which you will be shown the following screen:</p>
<figure><img src="@source/assets/images/verify-contract.png" alt="Smart Contract Verification page!" tabindex="0" loading="lazy"><figcaption>verify contract</figcaption></figure>
<TocHeader /><TOC class="table-of-contents" :include-level="[2,3]" /><h3 id="enter-contract-details" tabindex="-1"><a class="header-anchor" href="#enter-contract-details" aria-hidden="true">#</a> Enter contract details</h3>
<p>To verify the contract, enter the following details;</p>
<ul>
<li>Contract address: The address provided must match with the <code v-pre>0x</code> address generated during contract creation.</li>
<li>Contract name: The name must be identical to the name provided in the contract.</li>
<li>Optimization: This checks whether or not optimization was used while compiling the contract. If you enabled optimization during compilation, check <strong>Yes</strong> otherwise select <strong>No</strong></li>
<li>Solidity compiler version(Solc): This specifies the exact version of the compiler used to compile a smart contract. Click on the dropdown to specify the compiler version used. We encourage you to use version <code v-pre>0.8.16</code>.</li>
<li>zkSync compiler version(Zksolc): The zkSync compiler version used, the default is set to <code v-pre>v1.2.0</code>.</li>
</ul>
<br>
<figure><img src="@source/assets/images/compiler-version.png" alt="Compiler version!" tabindex="0" loading="lazy"><figcaption>compiler version</figcaption></figure>
<ul>
<li>
<p>Enter the Solidity Contract code: Copy the code from your editor and paste it into the text area.
<br>
<strong>Note:</strong> You may need to flatten your Solidity code if it utilizes a library or inherits dependencies from another contract.
<br>
We recommend using <a href="https://medium.com/coinmonks/flattening-smart-contracts-using-hardhat-dffe7dbc7b3f" target="_blank" rel="noopener noreferrer">Hardhat flatten<ExternalLinkIcon/></a>, <a href="https://github.com/NomicFoundation/truffle-flattener" target="_blank" rel="noopener noreferrer">Truffle flattener<ExternalLinkIcon/></a> or the <a href="https://github.com/poanetwork/solidity-flattener" target="_blank" rel="noopener noreferrer">POA Solidity flattener<ExternalLinkIcon/></a>.</p>
</li>
<li>
<p>Constructor arguments: If constructor arguments are required by the contract, you should add them here, but in <a href="https://solidity.readthedocs.io/en/develop/abi-spec.html" target="_blank" rel="noopener noreferrer">ABI hex-encoded form<ExternalLinkIcon/></a>.</p>
</li>
</ul>
<br>
<h3 id="how-can-you-obtain-your-constructor-arguments" tabindex="-1"><a class="header-anchor" href="#how-can-you-obtain-your-constructor-arguments" aria-hidden="true">#</a> How can you obtain your constructor arguments?</h3>
<blockquote>
<p><strong>Note:</strong> The easiest way to get the constructor argument data is to print it to the console while deploying.</p>
</blockquote>
<p>For example, if using our <RouterLink to="/dev/developer-guides/hello-world.html">tutorial</RouterLink>, you can find the line:</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">const</span> greeterContract <span class="token operator">=</span> <span class="token keyword">await</span> deployer<span class="token punctuation">.</span><span class="token function">deploy</span><span class="token punctuation">(</span>artifact<span class="token punctuation">,</span> <span class="token punctuation">[</span>greeting<span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>if you add the next line as</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code>console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>greeterContract<span class="token punctuation">.</span>interface<span class="token punctuation">.</span><span class="token function">encodeDeploy</span><span class="token punctuation">(</span><span class="token punctuation">[</span>greeting<span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>then you will receive constructor argument data.</p>
<ul>
<li>Lastly, click the <strong>Verify Smart Contract</strong> button.</li>
</ul>
<br>
If all goes well, you will see a success message.
<br>
<figure><img src="@source/assets/images/contract-verified.png" alt="Smart Contract Verified!" tabindex="0" loading="lazy"><figcaption>Contract Verified</figcaption></figure>
</div></template>


