export const data = JSON.parse("{\"key\":\"v-c76ba0b4\",\"path\":\"/api/python/getting-started.html\",\"title\":\"Getting started\",\"lang\":\"en-US\",\"frontmatter\":{\"description\":\"In this guide we will demonstrate how to: 1. Connect to the zkSync network. 2. Deposit assets from Ethereum into zkSync. 3. Check balances. 4. Transfer and withdraw funds (nativ...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/api/python/getting-started.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Getting started\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"In this guide we will demonstrate how to: 1. Connect to the zkSync network. 2. Deposit assets from Ethereum into zkSync. 3. Check balances. 4. Transfer and withdraw funds (nativ...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}]]},\"headers\":[{\"level\":2,\"title\":\"Prerequisite\",\"slug\":\"prerequisite\",\"link\":\"#prerequisite\",\"children\":[]},{\"level\":2,\"title\":\"Installation\",\"slug\":\"installation\",\"link\":\"#installation\",\"children\":[]},{\"level\":2,\"title\":\"Instantiating the SDK\",\"slug\":\"instantiating-the-sdk\",\"link\":\"#instantiating-the-sdk\",\"children\":[]},{\"level\":2,\"title\":\"Ethereum signer\",\"slug\":\"ethereum-signer\",\"link\":\"#ethereum-signer\",\"children\":[]},{\"level\":2,\"title\":\"Depositing funds\",\"slug\":\"depositing-funds\",\"link\":\"#depositing-funds\",\"children\":[]},{\"level\":2,\"title\":\"Checking balance\",\"slug\":\"checking-balance\",\"link\":\"#checking-balance\",\"children\":[]},{\"level\":2,\"title\":\"Performing a transfer\",\"slug\":\"performing-a-transfer\",\"link\":\"#performing-a-transfer\",\"children\":[]},{\"level\":2,\"title\":\"Transfer funds (ERC20 tokens)\",\"slug\":\"transfer-funds-erc20-tokens\",\"link\":\"#transfer-funds-erc20-tokens\",\"children\":[]},{\"level\":2,\"title\":\"Withdrawing funds\",\"slug\":\"withdrawing-funds\",\"link\":\"#withdrawing-funds\",\"children\":[]},{\"level\":2,\"title\":\"Deploy a smart contract\",\"slug\":\"deploy-a-smart-contract\",\"link\":\"#deploy-a-smart-contract\",\"children\":[{\"level\":3,\"title\":\"Step1: Create a contract\",\"slug\":\"step1-create-a-contract\",\"link\":\"#step1-create-a-contract\",\"children\":[]},{\"level\":3,\"title\":\"Step 2: Deploy the contract\",\"slug\":\"step-2-deploy-the-contract\",\"link\":\"#step-2-deploy-the-contract\",\"children\":[]}]},{\"level\":2,\"title\":\"Deploy a smart contract with Create2\",\"slug\":\"deploy-a-smart-contract-with-create2\",\"link\":\"#deploy-a-smart-contract-with-create2\",\"children\":[]}],\"readingTime\":{\"minutes\":5.84,\"words\":1752},\"filePathRelative\":\"api/python/getting-started.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
