export const pagesRoutes = [
  ["v-8daa1a0e","/",{"y":"h","title":"Quickstart"},["/index.html","/README.md"]],
  ["v-6d34f632","/contact.html",{"y":"a","title":"Contact and media"},["/contact","/contact.md"]],
  ["v-2e3eac9e","/slides.html",{"y":"s","title":"Slide page","i":"slides"},["/slides","/slides.md"]],
  ["v-744497ce","/api/",{"y":"a","title":"Overview"},["/api/index.html","/api/README.md"]],
  ["v-587e1e66","/api/api.html",{"y":"a","title":"Web3 API"},["/api/api","/api/api.md"]],
  ["v-59ea39b4","/api/contracts.html",{"y":"a","title":"L1 contracts interface"},["/api/contracts","/api/contracts.md"]],
  ["v-1473bf53","/demo/",{"y":"a","title":"Features Demo","i":"discover"},["/demo/index.html","/demo/README.md"]],
  ["v-4e65ec78","/demo/disable.html",{"y":"a","title":"Disabling layout and features","i":"config"},["/demo/disable","/demo/disable.md"]],
  ["v-c151bf32","/demo/encrypt.html",{"y":"a","title":"Encryption Article","i":"lock"},["/demo/encrypt","/demo/encrypt.md"]],
  ["v-438ffe52","/demo/markdown.html",{"y":"a","title":"Markdown Enhance","i":"markdown"},["/demo/markdown","/demo/markdown.md"]],
  ["v-6e19edb7","/demo/page.html",{"y":"a","title":"Page Config","i":"page"},["/demo/page","/demo/page.md"]],
  ["v-7445cd33","/dev/",{"y":"a","title":"zkSync Documentation"},["/dev/index.html","/dev/README.md"]],
  ["v-fffb8e28","/guide/",{"y":"a","title":"Guide","i":"creative"},["/guide/index.html","/guide/README.md"]],
  ["v-2d0ad528","/zh/",{"y":"h","title":"项目主页","i":"home"},["/zh/index.html","/zh/README.md"]],
  ["v-269ae70f","/zh/slides.html",{"y":"s","title":"幻灯片页","i":"slides"},["/zh/slides","/zh/slides.md"]],
  ["v-3a3f3db9","/api/go/",{"y":"a","title":"Go SDK"},["/api/go/index.html","/api/go/README.md"]],
  ["v-36881c1a","/api/go/getting-started.html",{"y":"a","title":"Getting started"},["/api/go/getting-started","/api/go/getting-started.md"]],
  ["v-b88003a6","/api/hardhat/",{"y":"a","title":"Hardhat plugins for zkSync 2.0"},["/api/hardhat/index.html","/api/hardhat/README.md"]],
  ["v-798e9e4a","/api/hardhat/compiling-libraries.html",{"y":"a","title":"Compiling non-inlinable libraries"},["/api/hardhat/compiling-libraries","/api/hardhat/compiling-libraries.md"]],
  ["v-4d781a8e","/api/hardhat/getting-started.html",{"y":"a","title":"Getting started"},["/api/hardhat/getting-started","/api/hardhat/getting-started.md"]],
  ["v-f970a034","/api/hardhat/plugins.html",{"y":"a","title":"Plugins"},["/api/hardhat/plugins","/api/hardhat/plugins.md"]],
  ["v-1a39fb76","/api/hardhat/testing.html",{"y":"a","title":"Local testing"},["/api/hardhat/testing","/api/hardhat/testing.md"]],
  ["v-59ad8f45","/api/python/",{"y":"a","title":"Python SDK"},["/api/python/index.html","/api/python/README.md"]],
  ["v-c76ba0b4","/api/python/getting-started.html",{"y":"a","title":"Getting started"},["/api/python/getting-started","/api/python/getting-started.md"]],
  ["v-b0e89982","/api/java/",{"y":"a","title":"Java SDK"},["/api/java/index.html","/api/java/README.md"]],
  ["v-f3cedac0","/api/java/getting-started.html",{"y":"a","title":"Getting started"},["/api/java/getting-started","/api/java/getting-started.md"]],
  ["v-3a3f4978","/api/js/",{"y":"a","title":"JS Web3 SDK"},["/api/js/index.html","/api/js/README.md"]],
  ["v-2212629a","/api/js/accounts-l1-l2.html",{"y":"a","title":"Accounts: L1->L2 transactions"},["/api/js/accounts-l1-l2","/api/js/accounts-l1-l2.md"]],
  ["v-7cee438a","/api/js/accounts.html",{"y":"a","title":"Accounts: overview"},["/api/js/accounts","/api/js/accounts.md"]],
  ["v-089f3960","/api/js/contracts.html",{"y":"a","title":"Contracts"},["/api/js/contracts","/api/js/contracts.md"]],
  ["v-c9af5778","/api/js/features.html",{"y":"a","title":"zkSync features"},["/api/js/features","/api/js/features.md"]],
  ["v-3a98e37a","/api/js/front-end.html",{"y":"a","title":"Front-end integration"},["/api/js/front-end","/api/js/front-end.md"]],
  ["v-2f33d259","/api/js/getting-started.html",{"y":"a","title":"Getting started"},["/api/js/getting-started","/api/js/getting-started.md"]],
  ["v-05b41622","/api/js/providers.html",{"y":"a","title":"Providers"},["/api/js/providers","/api/js/providers.md"]],
  ["v-d0c9c110","/api/js/types.html",{"y":"a","title":"Types"},["/api/js/types","/api/js/types.md"]],
  ["v-41b1ca40","/api/js/utils.html",{"y":"a","title":"Utilities"},["/api/js/utils","/api/js/utils.md"]],
  ["v-48a88b7c","/dev/developer-guides/",{"y":"a","title":"Understanding zkSync"},["/dev/developer-guides/index.html","/dev/developer-guides/README.md"]],
  ["v-57cf3f92","/dev/developer-guides/aa.html",{"y":"a","title":"Account abstraction support"},["/dev/developer-guides/aa","/dev/developer-guides/aa.md"]],
  ["v-1186fab8","/dev/developer-guides/hello-world.html",{"y":"a","title":"Quickstart"},["/dev/developer-guides/hello-world","/dev/developer-guides/hello-world.md"]],
  ["v-35a05ad2","/dev/developer-guides/security.html",{"y":"a","title":"Security model"},["/dev/developer-guides/security","/dev/developer-guides/security.md"]],
  ["v-0a7cac64","/dev/fundamentals/",{"y":"a","title":"Foundational topics"},["/dev/fundamentals/index.html","/dev/fundamentals/README.md"]],
  ["v-589b2f51","/dev/fundamentals/faq.html",{"y":"a","title":"FAQ"},["/dev/fundamentals/faq","/dev/fundamentals/faq.md"]],
  ["v-4bb516ec","/dev/fundamentals/rollups.html",{"y":"a","title":"Intro to rollups"},["/dev/fundamentals/rollups","/dev/fundamentals/rollups.md"]],
  ["v-8211ee88","/dev/fundamentals/testnet.html",{"y":"a","title":"zkSync testnet"},["/dev/fundamentals/testnet","/dev/fundamentals/testnet.md"]],
  ["v-e8bc1f42","/dev/fundamentals/zkSync.html",{"y":"a","title":"zkSync basics"},["/dev/fundamentals/zkSync","/dev/fundamentals/zkSync.md"]],
  ["v-faf16966","/dev/testnet/migration-to-testnet-paymaster.html",{"y":"a","title":"Migration to the testnet paymaster"},["/dev/testnet/migration-to-testnet-paymaster","/dev/testnet/migration-to-testnet-paymaster.md"]],
  ["v-333d6048","/dev/troubleshooting/",{"y":"a","title":"Troubleshooting"},["/dev/troubleshooting/index.html","/dev/troubleshooting/README.md"]],
  ["v-20baf8da","/dev/troubleshooting/important-links.html",{"y":"a","title":"Important links"},["/dev/troubleshooting/important-links","/dev/troubleshooting/important-links.md"]],
  ["v-03e4738d","/dev/troubleshooting/known-issues.html",{"y":"a","title":"Known issues"},["/dev/troubleshooting/known-issues","/dev/troubleshooting/known-issues.md"]],
  ["v-36728a42","/dev/troubleshooting/status.html",{"y":"a","title":"Feature support status"},["/dev/troubleshooting/status","/dev/troubleshooting/status.md"]],
  ["v-5d5c2d30","/guide/bar/",{"y":"a","title":"Bar feature","i":"creative"},["/guide/bar/index.html","/guide/bar/README.md"]],
  ["v-177e1f06","/guide/bar/baz.html",{"y":"a","title":"Baz","i":"info"},["/guide/bar/baz","/guide/bar/baz.md"]],
  ["v-a4bdf926","/dev/tutorials/",{"y":"a","title":"Tutorials"},["/dev/tutorials/index.html","/dev/tutorials/README.md"]],
  ["v-0cd8ca55","/dev/tutorials/cross-chain-tutorial.html",{"y":"a","title":"Cross-chain governance"},["/dev/tutorials/cross-chain-tutorial","/dev/tutorials/cross-chain-tutorial.md"]],
  ["v-514a621d","/dev/tutorials/custom-aa-tutorial.html",{"y":"a","title":"Account abstraction"},["/dev/tutorials/custom-aa-tutorial","/dev/tutorials/custom-aa-tutorial.md"]],
  ["v-1054c109","/dev/tutorials/custom-paymaster-tutorial.html",{"y":"a","title":"Building custom paymaster"},["/dev/tutorials/custom-paymaster-tutorial","/dev/tutorials/custom-paymaster-tutorial.md"]],
  ["v-5d5821d6","/guide/foo/",{"y":"a","title":"Foo feature","i":"config"},["/guide/foo/index.html","/guide/foo/README.md"]],
  ["v-0b6fc5f8","/guide/foo/ray.html",{"y":"a","title":"Ray","i":"config"},["/guide/foo/ray","/guide/foo/ray.md"]],
  ["v-2b64e284","/zh/demo/",{"y":"a","title":"主要功能与配置演示","i":"discover"},["/zh/demo/index.html","/zh/demo/README.md"]],
  ["v-c1942916","/zh/demo/disable.html",{"y":"a","title":"布局与功能禁用","i":"config"},["/zh/demo/disable","/zh/demo/disable.md"]],
  ["v-65c00218","/zh/demo/encrypt.html",{"y":"a","title":"密码加密的文章","i":"lock"},["/zh/demo/encrypt","/zh/demo/encrypt.md"]],
  ["v-36295574","/zh/demo/markdown.html",{"y":"a","title":"Markdown 展示","i":"markdown"},["/zh/demo/markdown","/zh/demo/markdown.md"]],
  ["v-62ced1a6","/zh/demo/page.html",{"y":"a","title":"页面配置","i":"page"},["/zh/demo/page","/zh/demo/page.md"]],
  ["v-47357bdb","/zh/guide/",{"y":"a","title":"指南","i":"creative"},["/zh/guide/index.html","/zh/guide/README.md"]],
  ["v-0f41a164","/api/tools/block-explorer/",{"y":"a","title":"Block Explorer"},["/api/tools/block-explorer/index.html","/api/tools/block-explorer/README.md"]],
  ["v-7ff2e9f4","/api/tools/block-explorer/block-view.html",{"y":"a","title":"Browse blocks"},["/api/tools/block-explorer/block-view","/api/tools/block-explorer/block-view.md"]],
  ["v-18f3fd71","/api/tools/block-explorer/contract-verification.html",{"y":"a","title":"Contract Verification"},["/api/tools/block-explorer/contract-verification","/api/tools/block-explorer/contract-verification.md"]],
  ["v-1f50388a","/api/tools/block-explorer/intro.html",{"y":"a","title":"Using the Block Explorer"},["/api/tools/block-explorer/intro","/api/tools/block-explorer/intro.md"]],
  ["v-38e1f823","/api/tools/block-explorer/search.html",{"y":"a","title":"The search bar"},["/api/tools/block-explorer/search","/api/tools/block-explorer/search.md"]],
  ["v-2668b47c","/api/tools/block-explorer/zkevm.html",{"y":"a","title":""},["/api/tools/block-explorer/zkevm","/api/tools/block-explorer/zkevm.md"]],
  ["v-ac7202a4","/api/tools/zksync-cli/",{"y":"a","title":"zkSync CLI"},["/api/tools/zksync-cli/index.html","/api/tools/zksync-cli/README.md"]],
  ["v-fa3b106e","/dev/developer-guides/bridging/bridging-asset.html",{"y":"a","title":"Bridging assets"},["/dev/developer-guides/bridging/bridging-asset","/dev/developer-guides/bridging/bridging-asset.md"]],
  ["v-35d34302","/dev/developer-guides/bridging/l1-l2-interop.html",{"y":"a","title":"L1 / L2 Interoperability"},["/dev/developer-guides/bridging/l1-l2-interop","/dev/developer-guides/bridging/l1-l2-interop.md"]],
  ["v-4c9f24f2","/dev/developer-guides/bridging/l1-l2.html",{"y":"a","title":"L1 -> L2 communication"},["/dev/developer-guides/bridging/l1-l2","/dev/developer-guides/bridging/l1-l2.md"]],
  ["v-41a28958","/dev/developer-guides/bridging/l2-l1.html",{"y":"a","title":"L2 -> L1 communication"},["/dev/developer-guides/bridging/l2-l1","/dev/developer-guides/bridging/l2-l1.md"]],
  ["v-2b3b64a8","/dev/developer-guides/building-on-zksync/",{"y":"a","title":"Building on zkSync"},["/dev/developer-guides/building-on-zksync/index.html","/dev/developer-guides/building-on-zksync/README.md"]],
  ["v-10d45398","/dev/developer-guides/building-on-zksync/events.html",{"y":"a","title":"Handling events"},["/dev/developer-guides/building-on-zksync/events","/dev/developer-guides/building-on-zksync/events.md"]],
  ["v-a32e6080","/dev/developer-guides/building-on-zksync/rpc.html",{"y":"a","title":"JSON-RPC API"},["/dev/developer-guides/building-on-zksync/rpc","/dev/developer-guides/building-on-zksync/rpc.md"]],
  ["v-2f5ccb55","/dev/developer-guides/building-on-zksync/videos.html",{"y":"a","title":"Video resources"},["/dev/developer-guides/building-on-zksync/videos","/dev/developer-guides/building-on-zksync/videos.md"]],
  ["v-49f1ba13","/dev/developer-guides/contracts/contract-verification.html",{"y":"a","title":"Verify contracts"},["/dev/developer-guides/contracts/contract-verification","/dev/developer-guides/contracts/contract-verification.md"]],
  ["v-7e507a48","/dev/developer-guides/contracts/contracts.html",{"y":"a","title":"Contract deployment"},["/dev/developer-guides/contracts/contracts","/dev/developer-guides/contracts/contracts.md"]],
  ["v-187c36c6","/dev/developer-guides/contracts/system-contracts.html",{"y":"a","title":"System contracts"},["/dev/developer-guides/contracts/system-contracts","/dev/developer-guides/contracts/system-contracts.md"]],
  ["v-1f1e199b","/dev/developer-guides/transactions/blocks.html",{"y":"a","title":"Blocks"},["/dev/developer-guides/transactions/blocks","/dev/developer-guides/transactions/blocks.md"]],
  ["v-4da8d86f","/dev/developer-guides/transactions/fee-model.html",{"y":"a","title":"Fee mechanism"},["/dev/developer-guides/transactions/fee-model","/dev/developer-guides/transactions/fee-model.md"]],
  ["v-34a93da8","/dev/developer-guides/transactions/transactions.html",{"y":"a","title":"Transactions"},["/dev/developer-guides/transactions/transactions","/dev/developer-guides/transactions/transactions.md"]],
  ["v-ccfa04e6","/dev/troubleshooting/docs-contribution/community-resources.html",{"y":"a","title":""},["/dev/troubleshooting/docs-contribution/community-resources","/dev/troubleshooting/docs-contribution/community-resources.md"]],
  ["v-211a0ec9","/dev/troubleshooting/docs-contribution/docs.html",{"y":"a","title":"Contribute to documentation"},["/dev/troubleshooting/docs-contribution/docs","/dev/troubleshooting/docs-contribution/docs.md"]],
  ["v-763c1cd7","/zh/guide/bar/",{"y":"a","title":"Bar 功能","i":"creative"},["/zh/guide/bar/index.html","/zh/guide/bar/README.md"]],
  ["v-1e317375","/zh/guide/bar/baz.html",{"y":"a","title":"Baz","i":"info"},["/zh/guide/bar/baz","/zh/guide/bar/baz.md"]],
  ["v-763e2284","/zh/guide/foo/",{"y":"a","title":"Foo 功能","i":"config"},["/zh/guide/foo/index.html","/zh/guide/foo/README.md"]],
  ["v-00fb7173","/zh/guide/foo/ray.html",{"y":"a","title":"Ray","i":"config"},["/zh/guide/foo/ray","/zh/guide/foo/ray.md"]],
  ["v-3706649a","/404.html",{"y":"p","title":""},["/404"]],
]
