export const pagesRoutes = [
  ["v-8daa1a0e","/",{"y":"h","title":"Project home","i":"home"},["/index.html","/README.md"]],
  ["v-2e3eac9e","/slides.html",{"y":"s","title":"Slide page","i":"slides"},["/slides","/slides.md"]],
  ["v-1473bf53","/demo/",{"y":"a","title":"Features Demo","i":"discover"},["/demo/index.html","/demo/README.md"]],
  ["v-4e65ec78","/demo/disable.html",{"y":"a","title":"Disabling layout and features","i":"config"},["/demo/disable","/demo/disable.md"]],
  ["v-c151bf32","/demo/encrypt.html",{"y":"a","title":"Encryption Article","i":"lock"},["/demo/encrypt","/demo/encrypt.md"]],
  ["v-438ffe52","/demo/markdown.html",{"y":"a","title":"Markdown Enhance","i":"markdown"},["/demo/markdown","/demo/markdown.md"]],
  ["v-6e19edb7","/demo/page.html",{"y":"a","title":"Page Config","i":"page"},["/demo/page","/demo/page.md"]],
  ["v-fffb8e28","/guide/",{"y":"a","title":"Guide","i":"creative"},["/guide/index.html","/guide/README.md"]],
  ["v-2d0ad528","/zh/",{"y":"h","title":"项目主页","i":"home"},["/zh/index.html","/zh/README.md"]],
  ["v-269ae70f","/zh/slides.html",{"y":"s","title":"幻灯片页","i":"slides"},["/zh/slides","/zh/slides.md"]],
  ["v-5d5c2d30","/guide/bar/",{"y":"a","title":"Bar feature","i":"creative"},["/guide/bar/index.html","/guide/bar/README.md"]],
  ["v-177e1f06","/guide/bar/baz.html",{"y":"a","title":"Baz","i":"info"},["/guide/bar/baz","/guide/bar/baz.md"]],
  ["v-5d5821d6","/guide/foo/",{"y":"a","title":"Foo feature","i":"config"},["/guide/foo/index.html","/guide/foo/README.md"]],
  ["v-0b6fc5f8","/guide/foo/ray.html",{"y":"a","title":"Ray","i":"config"},["/guide/foo/ray","/guide/foo/ray.md"]],
  ["v-2b64e284","/zh/demo/",{"y":"a","title":"主要功能与配置演示","i":"discover"},["/zh/demo/index.html","/zh/demo/README.md"]],
  ["v-c1942916","/zh/demo/disable.html",{"y":"a","title":"布局与功能禁用","i":"config"},["/zh/demo/disable","/zh/demo/disable.md"]],
  ["v-65c00218","/zh/demo/encrypt.html",{"y":"a","title":"密码加密的文章","i":"lock"},["/zh/demo/encrypt","/zh/demo/encrypt.md"]],
  ["v-36295574","/zh/demo/markdown.html",{"y":"a","title":"Markdown 展示","i":"markdown"},["/zh/demo/markdown","/zh/demo/markdown.md"]],
  ["v-62ced1a6","/zh/demo/page.html",{"y":"a","title":"页面配置","i":"page"},["/zh/demo/page","/zh/demo/page.md"]],
  ["v-47357bdb","/zh/guide/",{"y":"a","title":"指南","i":"creative"},["/zh/guide/index.html","/zh/guide/README.md"]],
  ["v-763c1cd7","/zh/guide/bar/",{"y":"a","title":"Bar 功能","i":"creative"},["/zh/guide/bar/index.html","/zh/guide/bar/README.md"]],
  ["v-1e317375","/zh/guide/bar/baz.html",{"y":"a","title":"Baz","i":"info"},["/zh/guide/bar/baz","/zh/guide/bar/baz.md"]],
  ["v-763e2284","/zh/guide/foo/",{"y":"a","title":"Foo 功能","i":"config"},["/zh/guide/foo/index.html","/zh/guide/foo/README.md"]],
  ["v-00fb7173","/zh/guide/foo/ray.html",{"y":"a","title":"Ray","i":"config"},["/zh/guide/foo/ray","/zh/guide/foo/ray.md"]],
  ["v-3706649a","/404.html",{"y":"p","title":""},["/404"]],
]
